export const EVENTS = {
  PRODUCT_ADDED: 'PRODUCT_ADDED',
  PRODUCT_REMOVED: 'PRODUCT_REMOVED',
  CAMPAIGN_APPLIED: 'CAMPAIGN_APPLIED',
  CAMPAIGN_REMOVED: 'CAMPAIGN_REMOVED',
  NOTIFICATION: 'NOTIFICATION',
};
